### ISSUE TITLE
UMD Distribution Option

### ISSUE THREAD

**Issue by eiof** [TechniqueSoftware/react-json-schema#20]
Currently, the ReactJsonSchema distribution has to be used in a CommonJS capable environment. It may serve someone benefit for there to be a UMD distribution of ReactJsonSchema.

UMD = Universal Module Definition
> These are modules which are capable of working everywhere, be it in the client, on the server or elsewhere.
(https://github.com/umdjs/umd)

I propose we add a the UMD distribution under a new directory, `dist/umd`. Weback is capable of outputting the additional distribution at build time.

**Comment by eiof** [comment]
@ajay2507 I can't think of a reason to have separate builds, so that should be fine. I didn't realize until now that we aren't currently using Webpack to build. If we move our build process into Webpack, then we can define the `output` option to include UMD, which would support CommonJS, AMD and create a global variable. [Webpack's documentation](https://webpack.js.org/configuration/output/#module-definition-systems).

```js
output: {
  library: "ReactJsonSchema",
  libraryTarget: "umd"
}
```

**Comment by ajay2507** [comment]
@eiof  Yup. That would be great to integerate with Webpack.
