### ISSUE TITLE
Passing handler function as props

### ISSUE THREAD

**Issue by sirajulm** [TechniqueSoftware/react-json-schema#24]
@nlaffey @eiof 
Does the current implementation support passing handler functions as function names to the schema?

I'm able to work with the below scenario:

```
{
    component: 'MyComponent,
    onClick: this.handleClickingMe.bind(this),
}
```
This one is possible if I'm creating using the schema just within the Component.

But it is not working with the below scenario, where I'd like to save and load the schema from the DB. In such cases, it is not possible to put the function reference directly, it would require function names to be saved instead.
```
{
    component: 'MyComponent,
    onClick: 'handleClickingMe',
}
```
I'd suggest something like below:
```
{
    component: 'MyComponent,
    handlers: [
            onClick: 'handleClickingMe',
    ]

}
```
Would be good if you could throw some insights on this. I'll find time to contribute for the same.

**Comment by eiof** [comment]
I think that fits within the mission statement, "Configure and build views using JSON schemas mapped to React components." I'm open to this being supported. If you find time to put together a pull request, we can discuss it more.

**Comment by richbai90** [comment]
Just opened a PR for this request

**Comment by eiof** [comment]
See https://github.com/TechniqueSoftware/react-json-schema/issues/34#issuecomment-585451749
