### ISSUE TITLE
Demo example not working!!!

### ISSUE THREAD

**Issue by suraj9793** [TechniqueSoftware/react-json-schema#29]
I was trying to run your demo example, but it is not working post following your instructions. Could you please elaborate the configuration process bit more since I also feel I might be missing something. You can check the below image which is being displayed after making sure all the dependencies have been installed.
![image](https://user-images.githubusercontent.com/19777312/40282339-89705b7e-5c8b-11e8-80c7-6815513f17ee.png)

**Comment by eiof** [comment]
Thanks for submitting an issue. React was missing as a dependency.
