### ISSUE TITLE
Support private key for metadata

### ISSUE THREAD

**Issue by richbai90** [TechniqueSoftware/react-json-schema#33]
I'd like to be able to support a private key that could hold implementation specific details that aren't necessarily relevant for the final rendered state of the schema. An example would be that it would be convenient for updating the schema if every element had some type of internal id that we could map to. This wouldn't be the same as the `key` prop because it's not a key for dynamic children, but a special identifier to get straight to the component in the schema. I don't want every component I render to have an ID prop, so having a place to store implementation specific details like that, where they won't be included in the final render would be nice.

I was thinking something like this

```js
component : 'MyComponent',
'@meta' : {
  id: 'root',
}
```

which would render to this

```jsx
<MyComponent />
```

**Comment by richbai90** [comment]
I'll gladly open a PR for this issue once I know if it fits in the scope of the mission statement.

**Comment by eiof** [comment]
See https://github.com/TechniqueSoftware/react-json-schema/issues/34#issuecomment-585451749
