### ISSUE TITLE
Need Json file validator for Gulp

### ISSUE THREAD

**Issue by pandiantcsl** [TechniqueSoftware/react-json-schema#38]
We have bunch of JSON files which uses react-json-schema parser to parseSchema and render. We want to build Gulp task or any validator to validate the JSON files during build time.

**Comment by eiof** [comment]
react-json-schema will never own validation of JSON. There are a few validators configured for Gulp on npm. You can probably find one through this search: https://www.npmjs.com/search?q=gulp%20json

If you want to perform validation prior to rendering, I'd recommend looking into [jsonschema](https://www.npmjs.com/package/jsonschema).
