### ISSUE TITLE
Mapping fails

### ISSUE THREAD

**Issue by pamatulli81** [TechniqueSoftware/react-json-schema#40]
Hi,

I am using your nice plugin with a lot of satisfaction!

There is one issue when it comes to map an object literal using a pre-definite schema.

This is the required component structure:
const steps =
    [
      {name: 'Step 1', component: <Step1 />},
      {name: 'Step 2', component: <Step2 />},
      {name: 'Step 3', component: <Step3 />},
      {name: 'Step 4', component: <Step4 />},
      {name: 'Step 5', component: <Step5 />}
    ]

    <div className='step-progress'>
        <StepZilla steps={steps}/>
    </div>

I have tried to map it via following schema, but the Reference component is expecting an object literal with the following structure:
-  {name: 'Step 1', component: <Step1 />},

The issue is in the children part as this in not an object like expected. I have tried just using:
- "component": "AxQlikVisualization" but it give sme
Failed prop type: Invalid prop `steps[0].component` of type `string` supplied to `StepZilla`,

I am sure I miss out something...

{
    "component": "Container",
    "className": "Wizard",
    "children": [
        {
            "component": "AxStepWizard",
            "steps": [
                {
                    "name": "Step 1",
                    **"children": [
                        {
                            "component": "AxQlikVisualization"
                            
                        }
                    ]**
                }
            ]
        }
    ]
}

Can you please assist me in this?

Thanks and regards,
Patric

**Comment by eiof** [comment]
To clarify, are you saying that the component takes a prop of `component`?

If so, ReactJsonSchema is going to try to resolve a component. What you could do is wrap this component in another component so that you can alias the prop.

**Comment by pamatulli81** [comment]
All is fine, it is all about composition.
Thank you!
