### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by somecatdad** [TechniqueSoftware/react-json-schema#42]
What sort of level of effort are we talking about to enhance react-json-schema to support React Native usage? Would it even be possible to work in the native app component world as opposed to the DOM world?

**Comment by brooksbecton** [comment]
Someone could use React Native elements by adding RN elements to the `setComponentMap` call

``` js
const schema = {
  component: "CommentList",
  children: [
    {
      component: "Comment",
      author: "Pete Hunt",
      children: [{ component: "Text", text: "This is one comment" }]
    },
    {
      component: "Comment",
      author: "Jordan Walke",
      children: [{ component: "Text", text: "This is *another* comment" }]
    }
  ]
};

const view = new ReactJsonSchema();
view.setComponentMap({ CommentList, Comment, Text, View });
```

It makes me wonder if a user could just pass in the same DOM object from react-dom-factories that is 
happening in `resolveComponents` so this tool could be agnostic of ReactDOM or React Native

https://github.com/TechniqueSoftware/react-json-schema/blob/master/lib/ReactJsonSchema.js#L38

**Comment by eiof** [comment]
It's reasonable to remove react-dom-factories as a dependency and have users pass in components from `DOM`.
